version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/pg-init/init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: docker.io/bitnamilegacy/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9092'" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - kafka_data:/bitnami/kafka

  kafka-init:
    image: docker.io/bitnamilegacy/kafka:4.0.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition:
          service_healthy
    volumes:
      - ./docker/kafka-init/create_topics.sh:/create_topics.sh
    command: [ "/bin/bash", "/create_topics.sh" ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT

  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC_AI_REQUEST=ai.makePoints.request
      - KAFKA_TOPIC_AI_RESPONSE=ai.makePoints.response
      - KAFKA_GROUP_ID=api_gateway_group
      - USER_SERVICE_URL=http://user-service:8001
      - STATISTIC_SERVICE_URL=http://statistic-service:8002
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy

#  ai-service:
#    build: ./AI-service
#    container_name: ai-service
#    environment:
#      - KAFKA_BOOTSTRAP=kafka:9092
#    ports:
#      - "8004:8004"
#    depends_on:
#      kafka:
#        condition: service_healthy

  user-service:
    build: ./User-service
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=123
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  statistic-service:
    build: ./Statistic-service
    environment:
      - DB_NAME=statistic
      - DB_USER=user_user
      - DB_PASSWORD=123
      - DB_PORT=5432
      - DB_HOST=postgres
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC_AI_REQUEST=ai.makePoints.request
      - KAFKA_TOPIC_AI_RESPONSE=ai.makePoints.response
    container_name: statistic-service
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
      kafka:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    depends_on:
      - api-gateway
      - user-service

volumes:
  postgres_data:
  kafka_data:
