version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/pg-init/init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    volumes:
      - kafka_data:/bitnami/kafka

  kafka-init:
    image: bitnamilegacy/kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    volumes:
      - ./docker/kafka-init/create_topics.sh:/create_topics.sh
    command: [ "/bin/bash", "/create_topics.sh" ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT

#  backend:
#    build: ./backend
#      environment:
#        DATABASE_URL: ${DATABASE_URL}
#        DB_HOST: ${DB_HOST}
#        DB_PORT: ${DB_PORT}
#        DB_NAME: ${DB_NAME}
#        DB_USER: ${DB_USER}
#        DB_PASSWORD: ${DB_PASSWORD}
#        SSL_MODE: ${SSL_MODE}
#        REDIS_URL: ${REDIS_URL}
#        JWT_SECRET: ${JWT_SECRET}
#        API_KEY: ${API_KEY}
#        GIGACHAT_CLIENT_ID: ${GIGACHAT_CLIENT_ID}
#        GIGACHAT_CLIENT_SECRET: ${GIGACHAT_CLIENT_SECRET}
#        GIGACHAT_SCOPE: ${GIGACHAT_SCOPE}
#        AI_SERVICE: ${AI_SERVICE}
#    ports:
#      - "3000:3000"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    volumes:
#      - ./uploads:/app/uploads

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#      args:
#        VITE_API_URL: ${VITE_API_URL}
#    environment:
#      VITE_API_URL: ${VITE_API_URL}
#      VITE_WS_URL: ${VITE_WS_URL}
#    ports:
#      - "80:80"
#    depends_on:
#      - backend

volumes:
  postgres_data:
  kafka_data:
